### ISSUE TITLE
Update to latest Mocha@5

### ISSUE THREAD

**Issue by pietermees** [timdp/karma-mocha-iframes#1]
https://github.com/timdp/karma-mocha-iframes/blob/ac59c94d6e0dd3eb96fa7c0653e5fbdad865ef2a/package.json#L31 currently requires Mocha 4, while Mocha 5 has been out for a while

**Comment by timdp** [comment]
It's a peerDependency though. The code is still compatible with 4.x so I'd rather change it to `^4.0.0, ^5.0.0` so people can use either one. I take it you verified that everything still works with 5?

**Comment by pietermees** [comment]
Yeah, it looked like it, fine by me :)

**Comment by timdp** [comment]
Published as v0.5.2.
